// @ts-check
// This file is normally generated by Wails bindings.

export function CancelCurrentJob() {
  return window["go"]["main"]["App"]["CancelCurrentJob"]();
}

export function ClearReferenceAudio() {
  return window["go"]["main"]["App"]["ClearReferenceAudio"]();
}

export function GetState() {
  return window["go"]["main"]["App"]["GetState"]();
}

export function OpenPath(arg1) {
  return window["go"]["main"]["App"]["OpenPath"](arg1);
}

export function ReadTextFile(arg1) {
  return window["go"]["main"]["App"]["ReadTextFile"](arg1);
}

export function SelectOutputDir() {
  return window["go"]["main"]["App"]["SelectOutputDir"]();
}

export function SelectAudio() {
  return window["go"]["main"]["App"]["SelectAudio"]();
}

export function SelectReferenceAudio() {
  return window["go"]["main"]["App"]["SelectReferenceAudio"]();
}

export function StartProcessing() {
  return window["go"]["main"]["App"]["StartProcessing"]();
}

export function StartSynthesis(arg1) {
  return window["go"]["main"]["App"]["StartSynthesis"](arg1);
}

export function StartTranslation(arg1) {
  return window["go"]["main"]["App"]["StartTranslation"](arg1);
}
