// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelCurrentJob():Promise<main.JobState>;

export function CancelSynthesis():Promise<main.JobState>;

export function ClearReferenceAudio():Promise<main.JobState>;

export function GetState():Promise<main.JobState>;

export function ImportChineseTextFile():Promise<main.JobState>;

export function ImportEnglishTranscriptFile():Promise<main.JobState>;

export function OpenPath(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveReviewDraft(arg1:Array<main.ReviewTurn>):Promise<main.JobState>;

export function SelectAudio():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectReferenceAudio():Promise<string>;

export function StartProcessing():Promise<main.JobState>;

export function StartProofread(arg1:Array<main.ReviewTurn>):Promise<main.JobState>;

export function StartSynthesis(arg1:main.SynthesisOptions):Promise<main.JobState>;

export function StartTranslation(arg1:Array<main.ReviewTurn>):Promise<main.JobState>;
