// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCurrentJob() {
  return window['go']['main']['App']['CancelCurrentJob']();
}

export function CancelSynthesis() {
  return window['go']['main']['App']['CancelSynthesis']();
}

export function ClearReferenceAudio() {
  return window['go']['main']['App']['ClearReferenceAudio']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportChineseTextFile() {
  return window['go']['main']['App']['ImportChineseTextFile']();
}

export function ImportEnglishTranscriptFile() {
  return window['go']['main']['App']['ImportEnglishTranscriptFile']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveReviewDraft(arg1) {
  return window['go']['main']['App']['SaveReviewDraft'](arg1);
}

export function SelectAudio() {
  return window['go']['main']['App']['SelectAudio']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectReferenceAudio() {
  return window['go']['main']['App']['SelectReferenceAudio']();
}

export function StartProcessing() {
  return window['go']['main']['App']['StartProcessing']();
}

export function StartProofread(arg1) {
  return window['go']['main']['App']['StartProofread'](arg1);
}

export function StartSynthesis(arg1) {
  return window['go']['main']['App']['StartSynthesis'](arg1);
}

export function StartTranslation(arg1) {
  return window['go']['main']['App']['StartTranslation'](arg1);
}
